fix smudge mode
Problem: Smudge creates an exception on my phone because of the unsupported element type.
                  android.renderscript.RSIllegalArgumentException: Unsuported element type.
                      at android.renderscript.ScriptIntrinsicBlur.create(ScriptIntrinsicBlur.java:50)
                      at anupam.acrylic.EasyPaint.onOptionsItemSelected(EasyPaint.java:414)
Solution: Wrap the code and catch the error, use a supported element type close to the one used.
Result: Smudge works and does not crash the app.